<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'TranslatewikiManagementExportWorkflow' => 'management/TranslatewikiManagementExportWorkflow.php',
    'TranslatewikiManagementGenerateWorkflow' => 'management/TranslatewikiManagementGenerateWorkflow.php',
    'TranslatewikiManagementWorkflow' => 'management/TranslatewikiManagementWorkflow.php',
  ),
  'function' => array(),
  'xmap' => array(
    'TranslatewikiManagementExportWorkflow' => 'TranslatewikiManagementWorkflow',
    'TranslatewikiManagementGenerateWorkflow' => 'TranslatewikiManagementWorkflow',
    'TranslatewikiManagementWorkflow' => 'PhutilArgumentWorkflow',
  ),
));
